ALTER TABLE company_config ADD COLUMN IF NOT EXISTS costing_method VARCHAR(20) DEFAULT 'WEIGHTED_AVERAGE';
ALTER TABLE company_config ADD COLUMN IF NOT EXISTS overhead_allocation_base VARCHAR(10) DEFAULT 'MOD';
ALTER TABLE company_config ADD COLUMN IF NOT EXISTS overhead_rate NUMERIC(5,2) DEFAULT 0;
