CREATE TABLE IF NOT EXISTS machinery (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    machinery_type VARCHAR(30) NOT NULL
        CHECK (machinery_type IN ('MOLINO','MEZCLADORA','EMBUTIDORA','AHUMADOR','EMPACADORA','SELLADORA','BASCULA','OTHER')),
    status VARCHAR(20) NOT NULL DEFAULT 'OPERATIONAL'
        CHECK (status IN ('OPERATIONAL','MAINTENANCE','DECOMMISSIONED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
